using UnityEngine;

namespace Utils {
    public class Singleton<T> : MonoBehaviour where T : MonoBehaviour {
        protected static T instance;
        public static T Instance {
            get {
                if (instance == null) {
                    instance = FindObjectOfType<T>();
                    if (instance == null) {
                        var go = new GameObject($"{typeof(T)} AutoGenerated");
                        instance = go.AddComponent<T>();
                    }
                }
                return instance;
            }
        }
    }
}

